development:
  adapter: postgresql
  encoding: unicode
  database: delta
  username: deploy
  password: ax6kai
  host: 127.1.1.1
  min_messages: WARNING
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: delta
  username: deploy
  password: ax6kai
  host: 127.1.1.1
  min_messages: WARNING
  pool: 5
